server:
  port: 8089

spring:
  application:
    name: client-service
  datasource:
    url: jdbc:postgresql://localhost:5434/clientdb
    username: clientuser
    password: clientpass
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
